name: Node.js CI-2

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
#   workflow_dispatch:

jobs:
  main: 
    uses: inders-poc/centralized-workflows/.github/workflows/main.yml@main

